#!/bin/bash

. $WM_PROJECT_DIR/bin/tools/RunFunctions

./Allclean
# create the mesh
# compute variables
radius=0.003 # radius 
theta=5 # full opening angle of the wedge
hA=0.001 # height of phase A

nr=10 # number of cells in radial direction
nhA=10 # number of cells in height direction of phase A


### start of program ###
pi=$(echo "scale=10; 4*a(1)" | bc -l)

radHalfTheta=$(echo "$theta*2.0*$pi/180.0" | bc -l);
t=$(echo "$radius*s($radHalfTheta)" | bc -l);
l=$(echo "$radius*c($radHalfTheta)" | bc -l);
mt=$(echo "(-1)*$t" | bc );
center=$(echo "(1.0)*$hA" | bc );
eps=$(echo "$hA*0.1" | bc -l);
phA=$(echo "$hA+$eps" | bc -l);
mhA=$(echo "$hA-$eps" | bc -l);

# make a copy from template and place stuff in there
cp constant/polyMesh/blockMeshDict.template constant/polyMesh/blockMeshDict
sed -i "s/OPT_l/$l/" constant/polyMesh/blockMeshDict
sed -i "s/OPT_t/$t/" constant/polyMesh/blockMeshDict
sed -i "s/OPT_mt/$mt/" constant/polyMesh/blockMeshDict
sed -i "s/OPT_hA/$hA/" constant/polyMesh/blockMeshDict
sed -i "s/OPT_center/$center/" constant/polyMesh/blockMeshDict
sed -i "s/OPT_nr/$nr/" constant/polyMesh/blockMeshDict
sed -i "s/OPT_nhA/$nhA/" constant/polyMesh/blockMeshDict

# run blockMesh to create wedge
runApplication blockMesh

# set up the extrudeProperties
cp constant/extrudeProperties.template constant/extrudeProperties
sed -i "s/OPT_angle/360/" constant/extrudeProperties # 360 for the full cylinder

# number of layers should be the number of opening angles
layers=$(echo "360/$theta" | bc);
sed -i "s/OPT_layers/$layers/" constant/extrudeProperties
runApplication extrudeMesh

runApplication setSet -batch constant/polyMesh/setBatch

runApplication createPatch -overwrite # overwrite runs over the constant/polyMesh folder

rm wedgePos.sMesh > /dev/null 2<&1
